aragon/radspec

src/index.js
Got removed as part of this commit: https://github.com/aragon/radspec/commit/f4f578364425474459891724d30050655b016b23
=> Fix removed evaluator import in entrypoint

package-lock.json, package.json, src/evaluator/index.js, src/parser/index.js, src/scanner/index.js, test/examples/examples.js, test/scanner/numbers.js, test/types/bytes.js
- Adds new token `HEXADECIMAL`
- Add new AST node `BytesLiteral` (transformed from `HEXADECIMAL` tokens)
- Check that targets in call expressions are actually addresses (`address` or `bytes20`)
Closes #9
=> Support bytes and address literals

package-lock.json, package.json
Pins web3 to the same version as all of our other repos.
Note that `websocket` is added as a dev dependency to fix travis builds, which oddly isn't able to install it now that [Fabian updated his branch to master](https://github.com/frozeman/WebSocket-Node/commit/6c72925e3f8aaaea8dc8450f97627e85263999f2)...
=> Pin web3.js to 1.0.0-beta.33

src/evaluator/index.js, src/parser/index.js, src/scanner/index.js, test/examples/examples.js, test/scanner/doubles.js
Useful for not duplicating a web3 call.
```
Set control from `owned.owner() || 'no one'` to `sender`
```
Attempts to be useful for all types.
=> Add default operator

src/evaluator/index.js, src/parser/index.js, src/types/bytes.js, src/types/index.js, test/examples/examples.js
Close #39 
For addresses and bytes types always converts to `BN`, comparisons are allowed even if the bytes are not of the same size, the numeric value will be used directly. Addresses can be compared with byte types of sizes less than or equal 20.
=> Implement equality and inequality comparisons for integers, addresses and bytesX

docs/API.md, package.json, src/index.js
Both `standard` and `documentation` require the globs to be in quotes for the glob to work properly :).
Also regens the documentation, since we haven't done it in a while.
=> Fix linting

.babelrc, .gitignore, package-lock.json, package.json, src/parser/index.js, test/examples/examples.js
Added a babel build step so we won't have to worry about which languages features we can use in this library.
The `radspec@1.0.0` release is broken because we used `object-rest-spread` D:
=> Add babel@7

package-lock.json, src/helpers/formatDate.js, src/helpers/transformTime.js
I think this actually allows `date-fns` to be tree-shaked, and it was also causing problems in bundled builds due to the require (parcel probably wasn't looking at the `modules` field in the package.json).
The rest of the codebase is still using `require()`, and I can change those over to `import` too so we don't get into this issue again.
=> Fix build due to improper importing of ES modules

package-lock.json, src/evaluator/index.js, test/examples/examples.js
Fix a crash when evaluating this expression:
```
Create a new upgradeable instance of `_appId` app linked to the Kernel, setting its code to `_appBase`. `_setDefault ? 'Also sets it as the default app instance.':''`
```
=> Fix evaluator crash with empty strings

src/data/knownFunctions.js, src/defaults.js, src/evaluator/index.js, src/helpers/lib/methodRegistry.js, src/helpers/radspec.js, test/examples/examples.js
When a function signature is not found on the local `knownFunctions.js` file, it checks Parity's [signature-registry](https://github.com/parity-contracts/signature-registry) to try to get the function name, which is what Metamask currently does for showing the function name in their signer.
=> @radspec: add fallback to Parity on-chain signature registry

src/data/knownFunctions.js, src/evaluator/index.js, src/helpers/HelperManager.js, src/helpers/index.js, src/helpers/radspec.js, src/index.js, src/lib/index.js, test/examples/examples.js
Builds on #62, #55.
Moves a few things around so the `@radspec` helper doesn't cause a circular dependency (unblocks #61).
Was looking into dynamic import instead of this but couldn't get it working with babel and it looked like parcel didn't support it very well anyway 🤷‍♂️.
=>  fix: Remove circular dependency and dynamic require for meta radspec

package-lock.json, src/data/knownFunctions.js, src/data/knownFunctions.json, src/defaults.js, src/evaluator/index.js, src/helpers/HelperManager.js, src/helpers/index.js, src/helpers/lib/methodRegistry.js, src/helpers/radspec.js, src/index.js, src/lib/index.js, src/scanner/index.js, src/types/bytes.js, test/examples/examples.js
The `@radspec` helper allows to recursively execute radspec as part of a radspec string. These strings should be either included in the radspec package or loaded from a trusted registry, as the recursive nature of this feature could be used to crash radspec with an infinite loop.
=> Implement @radspec helper

examples/README.md, examples/user-helpers/index.js, test/examples/examples.js, test/scanner/identifiers.js
In this way, we can define custom helper functions. Example:
```js
const radspec = require('../../src')
const web3 = require('web3-utils')
const expression = '`@toUtf8(gretting)` world.'
const bindings = {
gretting: {
type: 'bytes',
value: '0x48656c6c6f'
}
}
const options = {
userHelpers: {
toUtf8: () => async (hex) => {
return {
type: 'string',
value: web3.toUtf8(hex)
}
}
}
}
radspec.evaluateRaw(expression, bindings, options)
.then(console.log) // => "Hello world."
.catch(console.error)
```
=> Expose user helpers into evaluatorOptions

README.md
Please also update the repository tagline
> 🤘 Radspec is a safe interpreter for Ethereum's natspec
to
> 🤘 Radspec is a safe interpreter for Ethereum's NatSpec
=> Use preferred styling for NatSpec

test/examples/examples.js
Since these tests are also good examples for newcomes to radspec, it's a bit more clear what the actual radspec syntax is without escaped quotes.
=> tests: avoid escaped quotes for clarity

package.json, src/evaluator/index.js
The scrypt packages which is a dependency of web3-eth (and others) does not work with node.js >=11.15. This issue is already solved in https://github.com/ethereum/web3.js/pull/2938, so theoretically it should be sufficient to just update web3 to the latest 1.x version (which happens in this pull-request). Unfortunately, after this update, some of the tests fail :(
I did not have time to find the root cause of this, but just wanted to inform about my failing attempt.
Maybe in the meantime, add something like this to package.json?
```json
"engines": {
"node": ">=8.0.0 <=11.15.0"
},
```
I can confirm that it works with Node.js@10.16.3 (LTS)
=> Upgrade web3.js for latest node.js (<11) support

src/helpers/lib/formatBN.js, src/helpers/tokenAmount.js, test/examples/examples.js
In contrast to the comment on #77:
> I really like this! I would only push for having `precision` be set with a default (2 or 3), so it's _fairly_ similar to the current behaviour, and using `-1` or `null` to signify the precision as the token's decimal range.
I implemented the solution with the default precision set to `undefined`. It will break more tests if I go to the mentioned mode; precision set to 2 would break this for example:
```js
[{
source: 'Balance: `@tokenAmount(token, balance)`',
bindings: { token: address('0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359'), balance: int('10000000000000000000') }
}, 'Balance: 10 DAI'],
```
Anyways, I'm happy to change the behaviour to something else.
=> Precision from contract

src/helpers/lib/formatBN.js, test/examples/examples.js
cc @schmidsi.
Improves the precision changes, such that any truncation to the fraction results in a `~`.
Also makes the same fraction check more robust than the previous one.
=> Helpers: precision improvements

src/evaluator/index.js, src/index.js, test/examples/examples.js
closes #80 
- Passed tx sender and value to evaluator options
- Added check for `msg.sender` and `msg.value` as  a `PropertyAccessExpression`
Example of the syntax: 
```
Send `@tokenAmount(token, msg.value)` from `msg.sender` to `reciever`
```
where 
```
token = address(0)
```
=> msg sender and value bindings

package.json
Forgot to do this earlier, when we upgraded to the latest `web3.js@1`.
`web3.js` has stopped pinning it, so we should as well to avoid duplicate dependencies.
=> chore: unpin bn.js

src/data/decentraland/knownFunctions.js, src/data/index.js, src/helpers/radspec.js, test/examples/examples.js
I have added some functions to be tested by the agent.
```js
'setOwnerCutPerMillion(uint256)': 'Set marketplace fees to `$1 / 1000000`%',
'transferMarketplaceOwnership(address)':
'Transfer ownership of the marketplace to `$1`',
'transferOwnership(address)': 'Transfer ownership of the contract to `$1`',
'pause()': 'Pause contract',
'unpause()': 'Unpause Contract`'
```
=>  * feat: add dcl known functions to @radspec helper
